void sd_bus_add_match() {}
void sd_bus_call() {}
void sd_bus_call_async() {}
void sd_bus_call_method() {}
void sd_bus_can_send() {}
void sd_bus_close() {}
void sd_bus_creds_get_augmented_mask() {}
void sd_bus_creds_get_euid() {}
void sd_bus_creds_get_uid() {}
void sd_bus_creds_has_effective_cap() {}
void sd_bus_creds_ref() {}
void sd_bus_creds_unref() {}
void sd_bus_default_system() {}
void sd_bus_default_user() {}
void sd_bus_detach_event() {}
void sd_bus_emit_interfaces_added_strv() {}
void sd_bus_emit_interfaces_removed_strv() {}
void sd_bus_emit_properties_changed_strv() {}
void sd_bus_error_copy() {}
void sd_bus_error_free() {}
void sd_bus_error_get_errno() {}
void sd_bus_error_has_name() {}
void sd_bus_error_is_set() {}
void sd_bus_error_set() {}
void sd_bus_error_set_errno() {}
void sd_bus_error_set_errnofv() {}
void sd_bus_error_setf() {}
void sd_bus_flush() {}
void sd_bus_flush_close_unref() {}
void sd_bus_get_events() {}
void sd_bus_get_name_creds() {}
void sd_bus_get_owner_creds() {}
void sd_bus_get_timeout() {}
void sd_bus_message_append() {}
void sd_bus_message_append_array_space() {}
void sd_bus_message_append_basic() {}
void sd_bus_message_append_string_space() {}
void sd_bus_message_append_strv() {}
void sd_bus_message_close_container() {}
void sd_bus_message_copy() {}
void sd_bus_message_enter_container() {}
void sd_bus_message_exit_container() {}
void sd_bus_message_get_creds() {}
void sd_bus_message_get_destination() {}
void sd_bus_message_get_errno() {}
void sd_bus_message_get_interface() {}
void sd_bus_message_get_member() {}
void sd_bus_message_get_path() {}
void sd_bus_message_get_sender() {}
void sd_bus_message_get_signature() {}
void sd_bus_message_is_method_call() {}
void sd_bus_message_new_method_call() {}
void sd_bus_message_new_method_error() {}
void sd_bus_message_new_method_errorf() {}
void sd_bus_message_new_method_return() {}
void sd_bus_message_new_signal() {}
void sd_bus_message_open_container() {}
void sd_bus_message_peek_type() {}
void sd_bus_message_read() {}
void sd_bus_message_read_array() {}
void sd_bus_message_read_basic() {}
void sd_bus_message_read_strv() {}
void sd_bus_message_ref() {}
void sd_bus_message_rewind() {}
void sd_bus_message_set_auto_start() {}
void sd_bus_message_set_destination() {}
void sd_bus_message_skip() {}
void sd_bus_message_unref() {}
void sd_bus_new() {}
void sd_bus_open() {}
void sd_bus_open_system() {}
void sd_bus_open_user() {}
void sd_bus_process() {}
void sd_bus_query_sender_creds() {}
void sd_bus_query_sender_privilege() {}
void sd_bus_ref() {}
void sd_bus_reply_method_errno() {}
void sd_bus_reply_method_error() {}
void sd_bus_reply_method_errorf() {}
void sd_bus_reply_method_return() {}
void sd_bus_send() {}
void sd_bus_set_address() {}
void sd_bus_slot_ref() {}
void sd_bus_slot_unref() {}
void sd_bus_start() {}
void sd_bus_track_add_name() {}
void sd_bus_track_ref() {}
void sd_bus_track_remove_name() {}
void sd_bus_track_unref() {}
void sd_bus_unref() {}
void sd_bus_wait() {}
void sd_event_add_exit() {}
void sd_event_add_io() {}
void sd_event_add_time() {}
void sd_event_default() {}
void sd_event_dispatch() {}
void sd_event_exit() {}
void sd_event_get_tid() {}
void sd_event_new() {}
void sd_event_prepare() {}
void sd_event_ref() {}
void sd_event_run() {}
void sd_event_source_get_enabled() {}
void sd_event_source_get_event() {}
void sd_event_source_set_description() {}
void sd_event_source_set_enabled() {}
void sd_event_source_set_io_events() {}
void sd_event_source_set_io_fd() {}
void sd_event_source_set_prepare() {}
void sd_event_source_set_priority() {}
void sd_event_source_set_time() {}
void sd_event_source_unref() {}
void sd_event_unref() {}
void sd_event_wait() {}
void sd_id128_from_string() {}
void sd_id128_get_boot() {}
void sd_id128_get_machine() {}
void sd_id128_randomize() {}
void sd_id128_to_string() {}
void sd_is_socket() {}
void sd_journal_close() {}
void sd_journal_flush_matches() {}
void sd_journal_get_data() {}
void sd_journal_get_fd() {}
void sd_journal_get_timeout() {}
void sd_journal_printv() {}
void sd_journal_printv_with_location() {}
void sd_journal_process() {}
void sd_journal_sendv() {}
void sd_listen_fds() {}
void sd_notify() {}
void sd_pid_get_cgroup() {}
void sd_pid_get_session() {}
void sd_pid_notify() {}
void sd_pid_notify_with_fds() {}
void sd_session_get_seat() {}
void sd_watchdog_enabled() {}
